Repository OpenBlink/openblink-demo-m5, pull requests merged in 2025-03, with the labels that each got.

#1 Fix: Replace ESP.restart() with esp_restart() in ble_blink.c
  src/drv/ble_blink.c
Labels: bug

#2 docs: add mruby/c LED API documentation and example code to README
  README.md
Labels: documentation

#21 Localize README files: Add English, Chinese, and Japanese versions
  README
  README.ja.md
  README.md
  README.zh-CN.md
Labels: documentation

#25 fix for multiple environment
  platformio.ini
Labels: enhancement

#28 add an example to draw a mexican hat on LCD with adding Math support
  platformio.ini
  sample_rb/mexicanhat.rb
Labels: enhancement
